version: "3.3"
services:

  nginx:
    container_name: nginx
    build: nginx/
    ports:
      - "80:80"
    networks:
      internal_routes:
        aliases:
          - nginx

  rabbitmq_create_user:
    image: rabbitmq 
    ports:
      - "5672:5672"
    networks:
      internal_routes:
        aliases:
          - rabbitmq
  
  create_user:
    build: create_user/
    ports:
      - "5000:5000" 
    networks:
      internal_routes:
        aliases:
          - create_user
  list_user:
    container_name: api_luser
    build: list_user/
    networks:
      internal_routes:
        aliases:
          - list_user

  data:
    build: data/
    depends_on:
      - "rabbitmq_create_user"
    restart: on-failure
    networks:
      internal_routes:

  login:
    build: login/
    volumes: 
       - ./login/:/app
    expose:
       - 5002
    networks:
      internal_routes:
        aliases:
          - login             

  mongodb_replicate_set_1:
    container_name: rs1
    image: mongo:4.2
    command: mongod --replSet RS --port 27041 --dbpath /data/db --config /resource/mongod.yml
    volumes:
      - ./mongodb/data/rs1:/data/db
      - ./mongodb/mongod.yml:/resource/mongod.yml
    ports:
      - "27017:27041"
    networks:
      internal_routes:
        aliases:
          - rs1

  mongodb_replicate_set_2:
    container_name: rs2
    image: mongo:4.2
    command: mongod --replSet RS --port 27042 --dbpath /data/db --config /resource/mongod.yml
    volumes:
      - ./mongodb/data/rs2:/data/db
      - ./mongodb/mongod.yml:/resource/mongod.yml
    ports:
      - "27018:27042"
    networks:
      internal_routes:
        aliases:
          - rs2


  mongodb_replicate_set_3:
    container_name: rs3
    image: mongo:4.2
    command: mongod --replSet RS --port 27043 --dbpath /data/db --config /resource/mongod.yml
    volumes:
      - ./mongodb/data/rs3:/data/db
      - ./mongodb/mongod.yml:/resource/mongod.yml
    ports:
      - "27019:27043"
    networks:
      internal_routes:
        aliases:
          - rs3


  


networks:
  internal_routes:

